import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { RadixProvider } from "./rdt-provider";
import { ThemeProvider } from "./theme-provider";
import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <RadixProvider />
      <body>
        <ThemeProvider
          attribute="class"
          forcedTheme={"dark"}
          defaultTheme="dark"
          enableSystem
        >
          <Header />
          <main>
            <TRPCReactProvider>
              {children}
              <Toaster />
            </TRPCReactProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
